services:
  audivia-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./Audivia.API/appsettings.json:/app/appsettings.json:ro
    restart: always
